### ISSUE TITLE
Refactor MAGIC_Badpixels.py 

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/magic-cta-pipe#11]
Given that ctapipe_io_magic was refactored, I think some modules used in this repository can be also refactored. I looked through the `MAGIC_Badpixels.py` and have some ideas of the refactoring:

- it would be better to use the dictionary type for the output of the get_{badrmspixel, deadpixel}_mask function with the keys of the telescope IDs (M1: 1, M2: 2). This makes the Cal->DL1 script more readable. Currently the list type is returned and for example M1 mask is extracted as `mask[tel_id - 1] `. 
- since we now input only one subrun file, the observation ID will not change in a given run and so the `_check_new_run` function is not needed anymore.
- the `_getpixratiosqrt` just returns 1 and so is not needed anymore.

**Comment by aleberti** [comment]
Thank you for the inputs! Beside the refactoring, we should also think how this could be introduced in ctapipe. That way we could simply use the ctapipe-process tool. This would imply that also the MAGIC cleaning should be in ctapipe. There was a PR by Satoshi some time ago, I can check the status and possibly try to have it merged soon to be available in the next version of ctapipe.

**Comment by YoshikiOhtani** [comment]
OK thanks! I will start to refactor the code then and open a pull request later, but probably after the analysis school.

**Comment by aleberti** [comment]
> * since we now input only one subrun file, the observation ID will not change in a given run and so the `_check_new_run` function is not needed anymore.

this will be changed, because of the drive reports issue. It will be simpler to implement given the refactoring done in `ctapipe_io_magic`

> * the `_getpixratiosqrt` just returns 1 and so is not needed anymore.

yes, this assumes that we have the new MAGIC camera. I don't think we will introduce the old M1 camera (the one with hexagonal shape and with smaller pixels in the trigger region and bigger in the outer part) anyway.

**Comment by YoshikiOhtani** [comment]
> this will be changed, because of the drive reports issue. It will be simpler to implement given the refactoring done in `ctapipe_io_magic`

Hm, but even if the drive reports of all subrun files are read by ctapipe_io_magic, it doesn't change that we process the shower events subrun-wise, does it? This is why I thought the observation ID doesn't change.

**Comment by YoshikiOhtani** [comment]
I'm now looking into the code, especially about the dead pixels masking, and I would like to ask opinions before changing. If we use the current structure of the ctapipe_io_magic, we load the data files subrun-wise (even though we use process_run option "True", the MarsCalibratedRun object contains subrun-wise data). Based on the fact, the current "get_deadpixel_mask" function just loads the badpixel information from `event.mon.tel[tel_id].pixel_status.hardware_failing_pixels` and that's it. So I think we can simply remove this module, but what do you think? I will update also soon how the badrms pixels are treated.

**Comment by YoshikiOhtani** [comment]
OK so I also looked into the badrms pixels functions and for me everything can be done in ctapipe_io_magic and it would become more simpler. What I would like to propose is as follows:
- find the badrms pixels inside the MAGICEventSource and store its mask to `event.mon.tel[tel_id].pedestal.charge_std_outliers`. There are now three kinds of pedestal information, "Fundamental", "FromExtractor" and "FromExtractorRndm", but we can store every badrms pixels information by storing them with dictionary type.
- store the dead pixels information simply to `event.mon.tel[tel_id].pixel_status.hardware_failing_pixels`

then in the Cal->DL1 processes the badpixels mask can be simply extracted by:
```
badrmspixel_mask = event.mon.tel[tel_id].pedestal.charge_std_outliers['FromExtractorRndm']
deadpixel_mask = event.mon.tel[tel_id].pixel_status.hardware_failing_pixels
unsuitable_mask = np.logical_or(badrmspixel_mask, deadpixel_mask)
```

**Comment by YoshikiOhtani** [comment]
The function to calculate bad pixels is now implemented in the master branch of the `ctapipe_io_magic`. So I will close this issue.
