### ISSUE TITLE
Use of equivalent focal length?

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/magic-cta-pipe#136]
Hi, how are we dealing now with focal length in the reconstruction?

It seems that the focal length read from the MC files is the "effective" one, as opposed to "nominal" (called "equivalent" in ctapipe terms). On the other hand, I think real data (at least those of LST) contain only the nominal value, right?

**Comment by aleberti** [comment]
For MAGIC real data, the effective focal length is the default. It can be selected at the level of MAGICEventSource within ctapipe_io_magic.

**Comment by moralejo** [comment]
Ok, thanks @aleberti , I see:

https://github.com/cta-observatory/ctapipe_io_magic/blob/77ca709809e5ac12c8798e7491d86bb7bff15598/ctapipe_io_magic/__init__.py#L623-L631

I think however it is slightly wrong (shouldn't the nominal be 16.97 m ?) but that will have little effect. 
It is also a bit misleading to have it stored under "equivalent_focal_length". Once the ctapipe dependency is updated we should use the "effective_focal_length" field.
