### ISSUE TITLE
Normalization of EDISP

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/magic-cta-pipe#147]
@maxnoe reported that there is a problem in how the IRF files of energy dispersion are computed, namely the GDAF standard requires them to integrate to 1 instead of summing to 1 (see https://github.com/cta-observatory/pyirf/issues/249 for details)

I think we are having the same problem in the MCP chain, first of all because we are using (old, ~0.6.0) version of pyirf, so they are wrong at the moment of computing them, and second because in the interpolation we recalculate the normalization by using a simple sum:

https://github.com/cta-observatory/magic-cta-pipe/blob/1f27c608eba88bbe8fc9eb3c7ee588a0c9b3b50c/magicctapipe/scripts/lst1_magic/lst1_magic_dl2_to_dl3.py#L200-L205

**Comment by aleberti** [comment]
@jsitarek we can close this right? the new pyirf already includes this fix.
