### ISSUE TITLE
Rename scripts directory

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/magic-cta-pipe#15]
Is is OK for you @aleberti to rename the directories of the LST-1 + MAGIC analysis scripts, because the `lst1_magic_real` directory contains not only for real data analysis scripts but also the MC data analysis scripts (`lst1_magic_mc_dl0_to_dl1.py`, `lst1_magic_train_rfs.py`, `lst1_magic_dl1_to_dl2.py`) and so the current name is a bit strange. Probably, the `lst1_magic_mc` can be renamed something like `sensitivity` or `performance`, and then the `lst1_magic_real` can be renamed `lst1_magic`. What do you think?

**Comment by aleberti** [comment]
Fine for me, you can proceed to change it (please update the directory name in the README)
