### ISSUE TITLE
conversion of a MAGIC run to DL1 with a broken subrun

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/magic-cta-pipe#183]
using magic_calib_to_dl1.py fails when processing the whole run if one of the subruns has missing reports. 
an example is 20201214_M2_05093664.015_Y_CrabNebula-W0.40+035.root with no reports.
This fails when looking for Trigger tree to find the type of the run.
We could either skip the affected runs, or use the neighbouring reports: Drive is either way used for the whole run, while Trigger is not expected to change within the run (except of pathological cases).

**Comment by aleberti** [comment]
@jsitarek I think this should be opened in `ctapipe_io_magic`, it is something the event source should figure out.

**Comment by jsitarek** [comment]
true, I make an issue there: https://github.com/cta-observatory/ctapipe_io_magic/issues/85 and closing here
