### ISSUE TITLE
MAGIC analysis with MCP using sim_telarray MCs

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/magic-cta-pipe#20]
So far MAGIC analysis with MCP was done by using standard MAGIC MCs processed up to sorcerer level. 
To check things properly we need to have it working also for MCs that start at sim_telarray level (like it is done for LST1+MAGIC analysis)
The analysis scripts of @YoshikiOhtani can be adjusted for this

**Comment by YoshikiOhtani** [comment]
Sorry that I forgot to mention but the current combined analysis scripts in the master branch can be also used for MAGIC-only analysis with simtel MCs. After processing MAGIC calibrated data to DL1, one needs to merge telescope wise files with merge_hdf_files.py (i.e., dl1_M1 + dl1_M2 -> dl1_MAGIC) and apply the stereo reco scripts. The analysis flow after the stereo reco is the same as the combined analysis.

**Comment by aleberti** [comment]
Since this is working now with simtel MCs, I close the issue.
