### ISSUE TITLE
check_signal_from_dl2.ipynb does not work with mcp v0.4.1

### ISSUE THREAD

**Issue by aaguasca** [cta-observatory/magic-cta-pipe#212]
The Jupyter notebook [check_signal_from_dl2.ipynb](https://github.com/cta-observatory/magic-cta-pipe/blob/master/notebooks/check_signal_from_dl2.ipynb) does not work because the "get_stereo_events" function in the third code cell has to be updated with the argument "config" in it.

**Comment by Elisa-Visentin** [comment]
So sorryyyy!!! My fault, I never updated the notebooks after the pipeline upgrades we merged a few months ago. I just opened a new PR to fix it: #213

**Comment by Elisa-Visentin** [comment]
I think that this is solved now, right?

**Comment by aaguasca** [comment]
Yes, the Jupyter Notebook works fine with mcp v0.4.1 now. Thank you very much!
