### ISSUE TITLE
wrong combo_type  in check_signal_from_dl2.ipynb

### ISSUE THREAD

**Issue by SeiyaNozaki** [cta-observatory/magic-cta-pipe#262]
If I understand correctly, `combo_type` in `check_signal_from_dl2.ipynb` is not fixed after the definition of `combo_type` was changed.

**Comment by Elisa-Visentin** [comment]
Oh thanks I will open a PR to fix it (added to my ToDo list)

**Comment by Elisa-Visentin** [comment]
PR #263
