### ISSUE TITLE
impact calculation in magic-cta-pipe does not take into accout the zenith??

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/magic-cta-pipe#32]
Hi @YoshikiOhtani 

I found something fishy: 
https://github.com/cta-observatory/magic-cta-pipe/blob/d5dbecc39c3bb876c23ea00e4606c6589fcf439b/magicctapipe/image/cleaning.py#L688

it looks like the impact is computed in the GroundFrame that is oriented vertically and not the tilted frame, i.e. it is a distance measured on the ground and not the distance of the shower axis from the telescope position. At mid zenith, this is a considerable different.
It also neglects the z-axis position of the telescope

I guess the same is used for both training the energy estimation and applying it, so I'm not sure if it can produce some bias that can explain the 30% mismatch, but for sure it is spoiling the performance  at those zeniths.

**Comment by YoshikiOhtani** [comment]
Hi @jsitarek, actually I don't use this function in the combined analysis pipeline but uses the one that I personally developed:
https://github.com/cta-observatory/magic-cta-pipe/blob/d5dbecc39c3bb876c23ea00e4606c6589fcf439b/magicctapipe/utils/functions.py#L27

It calculates the distance between the shower axis and a telescope position (not on a ground frame). The equation is derived from my calculations by hand, but in the past I confirmed that the values obtained by this function are consistent with what MARS calculates, but I can double check it.

**Comment by jsitarek** [comment]
Hi @YoshikiOhtani 

good, but then we should remove the old function because it is very misleading (and either way calc_impact does not fit into cleaning.py file)

**Comment by YoshikiOhtani** [comment]
Hi @jsitarek, I see that this function is used in the scripts/performance/stereo_reco_MAGIC_LST.py developed by Davide for performance estimations with MCs, though these scripts have not been updated so long time (and not used recently?).

**Comment by jsitarek** [comment]
this is actually where I saw it, when I was looking if it is really used, but I think it would either way not work, because I do not see it imported from cleaning. If this script is still useful we can move to your function instead. Let's discuss on Wednesday.
One more thing, I could not find any place in the simtel MC files where the impacts are stored, only the core position is there. In your chain do you use the true impact position anywhere (like in creating the tables)? If so we should make sure that it is also calculated properly

**Comment by YoshikiOhtani** [comment]
Ah yes you are right, the function was in magicctapipe/reco/image.py but when I changed the structure of the repository I renamed and moved to the current directory magicctapipe/image/cleaning.py.

Then, as you said the SimulatedShowerContainer does not have a place to store the impact parameter:
https://github.com/cta-observatory/ctapipe/blob/9ee0635f92c40d38b3db9b7a6d8c866d951d51d2/ctapipe/containers.py#L460

So in my DL0 to DL1 chain, the true impact parameter is calculated with calc_impact function and is stored in a custom container, which is saved in an output file, though the current pipeline does not use the true values for any reconstructions:
https://github.com/cta-observatory/magic-cta-pipe/blob/d5dbecc39c3bb876c23ea00e4606c6589fcf439b/magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py#L361

**Comment by jsitarek** [comment]
I forgot to discuss it today in the meeting. I think either way I think we should remove the eval_impact function 
Is the stereo_reco_MAGIC_LST.py script still useful, or was it superseeded by another one? If it is still useful we should use your calc_impact function there instead. 
@davidedepaoli any feedback on this?

**Comment by davidedepaoli** [comment]
Yes, I think that the `stereo_reco_MAGIC_LST.py` script is still useful, and I am perfectly fine with removing the eval_impact function and use the other one instead
