### ISSUE TITLE
traitlets and jupyter inconsistency?

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/magic-cta-pipe#42]
I got a issue when updating the environment of mcp. 
conda complained on inconsistent traitlets version, i.e. setup.py of MCP requires 'traitlets~=5.0.5', while ipykernel wants > 5.1.
The effect is that while the MCP scripts work, jupyter kernel crashes. 
Anybody had a similar problem? 
Do we really need traitlets in this version, or can it be updated to a newer one?

**Comment by YoshikiOhtani** [comment]
Hi @jsitarek, I did not face this problem when setting up my environment. I checked their versions of my environment and ipykernel is 6.4.2, traitlets is 5.0.5. In the combined analysis scripts, trailtlets is used only in the process from mc DL0 to DL1, and I guess it works fine even if we update it to more than 5.1.

**Comment by jsitarek** [comment]
Hi @YoshikiOhtani  my ipykernel is 6.9.1
changing in setup.py traitlets version to 5.1.1 solves the problem with the jupyter  for me.
Probably we should either update the version of traitlets, or fix the ipykernel version to older

**Comment by YoshikiOhtani** [comment]
@aleberti do you know the reason why we fix the version of traitlets to ~5.0.5? We may be able to update it the newer version?

**Comment by aleberti** [comment]
It comes from `ctapipe` 0.12, where we have `"traitlets~=5.0,>=5.0.5"`. We then might fix ipykernel version. Anyhow it is strange, when installing the environment, in my case ipykernel version which gets installed is 6.4.2.

**Comment by YoshikiOhtani** [comment]
I have now updated my magic-cta-pipe environment with environment.yml of the current master branch, and it seems to install `traitlets-5.2.0` and `ipykernel-6.13.0`. However, when executing `pip install -e .` the versions are downgraded to `traitlets-5.0.5` and `ipykernel-6.4.2`, as the version of traitlets is specified in setpy.py. But I'm not sure why the version of ipykernel fixes 6.9.1 for Julian's case.

**Comment by jsitarek** [comment]
ipython and jupyter are listed in the environment without a specific version, as far as I can see there are also no specific requirements on their version in required packages (ctapipe, lstchain, ctapipe_io_magic), so I think this leaves more freedom in what is really installed and it might depend on the version of conda
