### ISSUE TITLE
Conflict in environment creation

### ISSUE THREAD

**Issue by gabemery** [cta-observatory/magic-cta-pipe#51]
I am trying to use the master environment.yml with `conda env create -f environment.yml` but conflicts are found.

**Comment by aleberti** [comment]
can you post which are the conflicts? I installed the environment last week and it went fine. The only change done was on the version of ctapipe_io_magic, which was updated to 0.4.2. Maybe it is related to #42?

**Comment by gabemery** [comment]
Conda tries to solve the conflicts but I interrupted before an answer (as it usually run for hours but I will leave it running for now)

conda env create -f environment.yml (--no-default-packages -v)
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.

**Comment by aleberti** [comment]
I see, then I will try as well.

**Comment by jsitarek** [comment]
> can you post which are the conflicts? I installed the environment last week and it went fine. The only change done was on the version of ctapipe_io_magic, which was updated to 0.4.2. Maybe it is related to #42?
 probably a different issue, because #42 happens not when you create the environment, but when you install MCP with pip inside it.

**Comment by aleberti** [comment]
I just tried and I have no conflicts. FYI I have miniconda3 with python 3.7.10, and conda 4.11.0.

**Comment by gabemery** [comment]
Ok thanks for trying, I will keep investigating on my side then.

**Comment by gabemery** [comment]
> 

Is this python 3.7.10 in a base environment over which you create the magic-cta-pipe environment or the one of your system, not used afterward?

**Comment by gabemery** [comment]
Update : I also didn't encountered the issue when installing on the La Palma cluster instead of locally. So the issue is probably not with magic-cta-pipe.

**Comment by aleberti** [comment]
> @aleberti
> 
> Is this python 3.7.10 in a base environment over which you create the magic-cta-pipe environment or the one of your system, not used afterward?

Yes, it is the python from the base environment. After activating it, within the environment python 3.7.7 is installed

**Comment by gabemery** [comment]
I solved my issue. It was from my local conda config file which used channel_priority: strict.
Changing to flexible removed the conflicts.
