### ISSUE TITLE
merging of linked files

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/magic-cta-pipe#61]
Hi @YoshikiOhtani 

does the "resolve()" in this line:
https://github.com/cta-observatory/magic-cta-pipe/blob/d2ff75598bdb7a9252cc325c3b387f8360f325d4/magicctapipe/scripts/lst1_magic/merge_hdf_files.py#L128
have intended meaning?

it follows the links, so when I tried to link the files and rename the links to follow the format accepted by the macro it did not work, because it still get the original file name. Removing "resolve()" worked fine in this case

**Comment by YoshikiOhtani** [comment]
Hi @jsitarek, sorry for being late to reply. I put `resolve()` so that the script works if one creates symbolic links with different names from the original files. But yes, it is fine for me to remove it for the case that the original files have different names from the expected regex.
