### ISSUE TITLE
Stereo MAGIC trigger condition

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/magic-cta-pipe#73]
I realized something that might be a bit of problem when working with sim_telarray MCs of LST1+MAGIC (like LSTProd2). 
Those productions are done with option -DNO_STEREO_TRIGGER=1, which needs to be there to keep LST1 mono events, but what we actually have are MAGIC stereo events. So it is possible e.g. to have a MC event in which LST1 and M1 triggered and M2 did not. Such an event can survive the full MCP analysis chain, and be reconstructed and add to Aeff, but it would not be present in the data since M1 mono event would not be saved. 
I guess this is not checked in the current chain, right? The check would be to filter out events without M1+M2 trigger, but this would need to be tested, because the trigger setting matching between MagicSoft and sim_telarray is not perfect.

**Comment by YoshikiOhtani** [comment]
Hi @jsitarek, indeed the current LST1 + MAGIC MCs are produced with the mono trigger condition, so all the events triggering any telescopes are saved. However, in the DL0 to DL1 process, as you might remember that the script gives `magic_stereo = True` if an event triggers both M1 and M2:

https://github.com/cta-observatory/magic-cta-pipe/blob/47e8a955b5ceb40dcd4867aecea990fb91b98f01/magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py#L267-L271

Then, when creating the IRFs this `magic_stereo` is used - if you specify the IRF type `software_with_any2`, it creates the IRFs with 3-tels and any 2 events that triggered both M1 and M2, extracted by applying the condition `magic_stereo == True`:

https://github.com/cta-observatory/magic-cta-pipe/blob/47e8a955b5ceb40dcd4867aecea990fb91b98f01/magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py#L120-L121

This software_with_any2 is actually needed to distinguish with the hardware trigger condition which has not yet been used in reality, so if you use the any 2 events that exist in the current real data, please create the IRFs with the `software_with_any2` type.

**Comment by YoshikiOhtani** [comment]
By the way, I was also wondering if the current MC trigger condition is fine or not. As far as I remember, in reality MAGIC uses the stereo trigger condition with which the events triggering both M1 and M2 in a given time window are only saved. However in the simulations I think we don't require such a timing condition, and so it may overestimate the effective area?

**Comment by jsitarek** [comment]
Hi @YoshikiOhtani thanks for a quick reply and for explaining that it is fine. I will close this issue then.

Concerning the stereo trigger simulation indeed there is no explicit condition in MagicSoft camera. As far as I remember the MAGIC stereo trigger coincidence window is a few hundred ns (I do not remember the exact number, I will check with HW guys), this is smaller compared to the window that you are using, but still much larger than the shower-intrinsic time spread (if geometrical effect of pointing is corrected!)
Look at the attached plot. I couldn't find the absolute trigger time in camera, so I plotted the first p.e. times. This is for ring wobble gammas with zenith 49-50 deg, for higher zeniths, diffuse MCs and protons will likely be broader.
![first_phot_time](https://user-images.githubusercontent.com/33022433/172146979-629bd2bf-7f03-4cdf-b244-604accdc0497.png)
You can see that bulk of the effect comes from the geometry, and the remaining spread is pretty small. 
The way how it is done on MAGIC HW side is that there are LUT for different positions of Az/Zd. So the actual accuracy depends on how fine are those tables made, and not on the shower physics.
