### ISSUE TITLE
Instruction written in README

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/magic-cta-pipe#8]
It seems the installation method written in README.md in the master branch should be updated a bit. The current instruction can creates the environment but user doesn't install the magic-cta-pipe directory. I think it should be as follows:

```
git clone https://github.com/cta-observatory/magic-cta-pipe.git
cd magic-cta-pipe
conda env create -n magic-lst1 -f environment.yml
conda activate magic-lst1
pip install .
```

**Comment by aleberti** [comment]
Yes, indeed. Another solution would be to create some entry points in the setup.py, so that magic_lst1 script can be called from anywhere. But I think I can implement this another time. Thanks for reporting!
