### ISSUE TITLE
Move functions to proper modules

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/magic-cta-pipe#88]
The functions used for the combined analysis are mostly defined inside the scripts that we usually run, except the RF estimators (= magicctapipe/reco/estimators.py) and some utils (magicctapipe/utils/functions.py). Now that the script starts to work reasonably, it may be good to move the functions to proper modules like lstchain, for example, move the `scripts.lst1_magic_mc_dl0_to_dl1.mc_dl0_to_dl1` function under magicctapipe/reco, and move `utils.functions.save_pandas_to_table` to magicctapipe/io, etc. What do you think @aleberti?

By the way if we do so, I think it would be also good to clean up the modules - maybe there are some functions that can be united inside one module or that are not used anymore.

**Comment by aleberti** [comment]
Yes, sure, I think it is a good approach. This would make changes to the used functions transparent to the user, so that the interface to the users remains the same.
